name: test
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Cache node_modules
              id: node-modules-cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              if: steps.node-modules-cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn test
